apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pxgc00exf-go 
  janus-idp.io/tekton: pxgc00exf-go
  backstage.io/kubernetes-id: pxgc00exf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pxgc00exf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  