apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pxgc00exf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pxgc00exf-go 
  name: pxgc00exf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pxgc00exf-go 
